#!/usr/bin/env node
'use strict';
/**
 * Generates database/seed.sql – DEMO data only (fictional agencies, people,
 * .example e-mail domains, Ofcom/NANP fictional phone ranges, no real PNRs).
 * All dates are relative to now() so the demo looks "live" whenever it is loaded.
 * Priorities, requirement summaries and quote texts are computed with the same
 * lib/ code the workflows use.
 *
 *   node scripts/generate-seed.js
 */
const fs = require('fs');
const path = require('path');
const { mergeRequirements } = require('../lib/requirements');
const { scorePriority } = require('../lib/priority');
const { routeToDesk } = require('../lib/routing');
const { getConfig } = require('../lib/config');
const { MockFareProvider } = require('../lib/providers/mockFareProvider');
const { validateFareOptions } = require('../lib/fares');
const Q = require('../lib/quote');
const { addDays } = require('../lib/dates');

const cfg = getConfig({});
const NOW = new Date();
const TODAY = NOW.toISOString().slice(0, 10);

const q = (v) => (v === null || v === undefined ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`);
const j = (v) => `${q(JSON.stringify(v))}::jsonb`;
const arr = (list) => (list && list.length ? `ARRAY[${list.map(q).join(', ')}]::text[]` : `'{}'::text[]`);
const ago = (minutes) => `now() - interval '${Math.round(minutes)} minutes'`;
const day = (offset) => (offset === null ? 'NULL' : `current_date + ${offset}`);
// Deterministic, readable demo UUIDs: <prefix padded to 20 hex chars><n padded to 12>
const uuid = (prefix, n) => `${prefix.padEnd(20, '0')}${String(n).padStart(12, '0')}`.replace(/^(.{8})(.{4})(.{4})(.{4})(.{12})$/, '$1-$2-$3-$4-$5');

const agencies = [
  ['Apex Travel', 'APEX', 'apex-travel.example', 'IN', 'VIP', 'email'],
  ['Globetrek Holidays', 'GLOBE', 'globetrek.example', 'IN', 'STANDARD', 'email'],
  ['Silverline Tours', 'SILVER', 'silverline-tours.example', 'AE', 'VIP', 'whatsapp'],
  ['Horizon Voyages', 'HORIZON', 'horizon-voyages.example', 'GB', 'STANDARD', 'email'],
  ['BlueSky Journeys', 'BLUESKY', 'bluesky-journeys.example', 'KE', 'STANDARD', 'whatsapp'],
  ['Meridian Corporate Travel', 'MERIDIAN', 'meridian-corp.example', 'GB', 'VIP', 'email'],
  ['Coral Coast Travel', 'CORAL', 'coralcoast.example', 'MU', 'STANDARD', 'whatsapp'],
  ['Northstar Trips', 'NORTH', 'northstar-trips.example', 'CA', 'STANDARD', 'email'],
  ['Saffron Routes', 'SAFFRON', 'saffron-routes.example', 'IN', 'STANDARD', 'whatsapp'],
  ['Atlas & Co Travel', 'ATLAS', 'atlasco.example', 'ZA', 'STANDARD', 'email'],
];

const people = [
  ['John', 'Carter'], ['Neha', 'Kapoor'], ['Priya', 'Nair'], ['Arjun', 'Mehta'], ['Omar', 'Haddad'], ['Layla', 'Farouk'],
  ['Emily', 'Hughes'], ['George', 'Bennett'], ['Wanjiru', 'Kamau'], ['Brian', 'Otieno'], ['Charlotte', 'Reid'], ['Marcus', 'Hale'],
  ['Anaïs', 'Ramdin'], ['Kevin', 'Li Wan Po'], ['Sophie', 'Tremblay'], ['Ethan', 'Brooks'], ['Meera', 'Shah'], ['Rohan', 'Iyer'],
  ['Thandi', 'Mokoena'], ['Pieter', 'van Wyk'],
];

const operators = [
  ['PREMIUM_DESK', 'Aisha Khan'], ['PREMIUM_DESK', 'Daniel Moreau'], ['GROUP_DESK', 'Ravi Menon'],
  ['TICKETING_DESK', 'Sofia Lindqvist'], ['TICKETING_DESK', 'Tom Okafor'], ['REFUND_DESK', 'Mei Tan'], ['GENERAL_DESK', 'Lucas Ferreira'],
];

const out = [];
out.push('-- =============================================================================');
out.push('-- DEMO DATA – generated by scripts/generate-seed.js. Fictional companies and people only.');
out.push('-- Do not edit by hand: change the generator and re-run it.');
out.push('-- =============================================================================');
out.push('BEGIN;');

operators.forEach(([desk, name], i) => {
  out.push(`INSERT INTO operators (id, desk_code, full_name, email) VALUES ('${uuid('00000000', 100 + i)}', ${q(desk)}, ${q(name)}, ${q(`${name.toLowerCase().replace(/[^a-z]+/g, '.')}@offshorefares.example`)});`);
});

agencies.forEach(([name, code, domain, country, prio, channel], i) => {
  out.push(`INSERT INTO agencies (id, name, code, email_domain, phone, country, priority_level, preferred_channel, is_demo) VALUES ('${uuid('0000000a', i + 1)}', ${q(name)}, ${q(code)}, ${q(domain)}, ${q(`+44 20 7946 0${String(100 + i).padStart(3, '0')}`)}, ${q(country)}, ${q(prio)}, ${q(channel)}, true);`);
});

const contacts = people.map(([first, last], i) => {
  const agencyIndex = Math.floor(i / 2);
  const agency = agencies[agencyIndex];
  const email = `${first.toLowerCase().normalize('NFD').replace(/[^a-z]/g, '')}.${last.toLowerCase().replace(/[^a-z]/g, '')}@${agency[2]}`;
  const wa = i % 2 === 0 ? `4477009001${String(i + 1).padStart(2, '0')}` : `1555555${String(100 + i).padStart(4, '0')}`;
  const id = uuid('0000000c', i + 1);
  out.push(`INSERT INTO contacts (id, agency_id, first_name, last_name, email, phone, whatsapp_phone, preferred_channel, is_demo) VALUES ('${id}', '${uuid('0000000a', agencyIndex + 1)}', ${q(first)}, ${q(last)}, ${q(email)}, ${q(`+${wa}`)}, ${q(wa)}, ${q(agency[5])}, true);`);
  return { id, first, last, email, wa, agencyIndex, agencyId: uuid('0000000a', agencyIndex + 1), vip: agency[4] === 'VIP' };
});

// 30 RFQs across the lifecycle --------------------------------------------------
// [contactIdx, origin, dest, depOffsetDays, retOffsetDays, adults, cabin, status, createdMinAgo, statusMinAgo, channel, extra]
const R = [
  [2, 'DEL', 'JFK', 21, 35, 2, 'BUSINESS', 'NEW', 2, 2, 'email', {}],
  [4, 'DXB', 'LHR', 12, 19, 1, 'FIRST', 'NEEDS_INFORMATION', 40, 38, 'whatsapp', { missingReturn: true }],
  [6, 'LHR', 'SIN', 30, null, 2, 'BUSINESS', 'NEEDS_INFORMATION', 95, 90, 'email', { missingPax: true }],
  [8, 'NBO', 'DXB', 9, 16, 4, 'BUSINESS', 'READY_FOR_SEARCH', 25, 22, 'whatsapp', {}],
  [0, 'BOM', 'DXB', 1, 6, 2, 'BUSINESS', 'TICKETED', 4320, 2880, 'email', { pnr: 'K7Q2LM' }],
  [10, 'LHR', 'JFK', 2, 5, 1, 'FIRST', 'ASSIGNED', 18, 14, 'email', { urgent: true }],
  [12, 'MRU', 'CDG', 40, 54, 3, 'BUSINESS', 'SEARCHING', 70, 35, 'whatsapp', {}],
  [14, 'YYZ', 'LHR', 25, 39, 2, 'PREMIUM_ECONOMY', 'SEARCHING', 120, 50, 'email', {}],
  [16, 'BOM', 'SIN', 18, 25, 2, 'BUSINESS', 'PENDING_APPROVAL', 160, 6, 'whatsapp', { quote: true }],
  [1, 'BLR', 'FRA', 33, 47, 1, 'BUSINESS', 'PENDING_APPROVAL', 200, 22, 'email', { quote: true }],
  [3, 'DEL', 'YYZ', 45, 70, 3, 'BUSINESS', 'AWAITING_CLIENT', 600, 300, 'email', { quote: true, sent: true }],
  [5, 'DXB', 'JFK', 14, 28, 2, 'FIRST', 'AWAITING_CLIENT', 1500, 1400, 'whatsapp', { quote: true, sent: true }],
  [7, 'LHR', 'DXB', 20, 27, 2, 'BUSINESS', 'AWAITING_CLIENT', 3000, 2900, 'email', { quote: true, sent: true, followups: 1 }],
  [9, 'NBO', 'LHR', 50, 64, 2, 'BUSINESS', 'CLIENT_INTERESTED', 2000, 600, 'whatsapp', { quote: true, sent: true }],
  [11, 'LHR', 'HKG', 7, 14, 1, 'BUSINESS', 'BOOKING_REQUESTED', 900, 3, 'email', { quote: true, sent: true, selected: 2 }],
  [13, 'MRU', 'DXB', 11, 18, 2, 'BUSINESS', 'TICKETING', 2500, 60, 'whatsapp', { quote: true, sent: true, selected: 1 }],
  [15, 'YUL', 'CDG', 60, 74, 2, 'BUSINESS', 'TICKETED', 7000, 4000, 'email', { quote: true, sent: true, selected: 1, pnr: 'PX4R8T' }],
  [17, 'BOM', 'LHR', 26, 40, 14, 'ECONOMY', 'SEARCHING', 300, 120, 'whatsapp', { group: true }],
  [18, 'JNB', 'LHR', 15, 29, 2, 'FIRST', 'TICKETED', 9000, 6000, 'email', { quote: true, sent: true, selected: 1, pnr: 'ZN5W3C' }],
  [19, 'CPT', 'DXB', 3, null, 1, 'BUSINESS', 'CHANGE_REQUESTED', 10000, 12, 'email', { pnr: 'H2J9KD', change: true }],
  [0, 'BOM', 'SIN', 38, 45, 2, 'BUSINESS', 'LOST', 12000, 8000, 'email', { quote: true, sent: true }],
  [2, 'DEL', 'LHR', 55, 69, 2, 'BUSINESS', 'CLOSED', 20000, 15000, 'email', { quote: true, sent: true, selected: 1, pnr: 'TQ7M2B' }],
  [4, 'DXB', 'CDG', 16, 23, 2, 'BUSINESS', 'CANCELLED', 5000, 4500, 'whatsapp', {}],
  [6, 'LHR', 'BOM', 8, 22, 1, 'BUSINESS', 'REFUND_REQUESTED', 14000, 30, 'email', { pnr: 'RF6N4A', refund: true }],
  [8, 'NBO', 'BOM', 27, 41, 2, 'ECONOMY', 'READY_FOR_SEARCH', 8, 8, 'whatsapp', {}],
  [10, 'LHR', 'MIA', 36, 50, 2, 'PREMIUM_ECONOMY', 'ASSIGNED', 45, 40, 'email', {}],
  [12, 'MRU', 'JNB', 13, 20, 1, 'BUSINESS', 'AWAITING_CLIENT', 400, 380, 'whatsapp', { quote: true, sent: true }],
  [14, 'YYZ', 'DEL', 42, 63, 4, 'BUSINESS', 'NEW', 1, 1, 'email', {}],
  [16, 'BOM', 'DOH', 4, 9, 2, 'FIRST', 'FARES_FOUND', 55, 4, 'whatsapp', { options: true }],
  [18, 'JNB', 'DXB', 24, 31, 2, 'BUSINESS', 'READY_FOR_SEARCH', 31, 28, 'email', { slaBreached: true }],
];

const PATHS = {
  NEW: ['NEW'],
  NEEDS_INFORMATION: ['NEW', 'NEEDS_INFORMATION'],
  READY_FOR_SEARCH: ['NEW', 'READY_FOR_SEARCH'],
  ASSIGNED: ['NEW', 'READY_FOR_SEARCH', 'ASSIGNED'],
  SEARCHING: ['NEW', 'READY_FOR_SEARCH', 'ASSIGNED', 'SEARCHING'],
  FARES_FOUND: ['NEW', 'READY_FOR_SEARCH', 'ASSIGNED', 'SEARCHING', 'FARES_FOUND'],
  PENDING_APPROVAL: ['NEW', 'READY_FOR_SEARCH', 'ASSIGNED', 'SEARCHING', 'FARES_FOUND', 'PENDING_APPROVAL'],
  AWAITING_CLIENT: ['NEW', 'READY_FOR_SEARCH', 'ASSIGNED', 'SEARCHING', 'FARES_FOUND', 'PENDING_APPROVAL', 'APPROVED', 'QUOTED', 'AWAITING_CLIENT'],
  CLIENT_INTERESTED: ['NEW', 'READY_FOR_SEARCH', 'ASSIGNED', 'SEARCHING', 'FARES_FOUND', 'PENDING_APPROVAL', 'APPROVED', 'QUOTED', 'AWAITING_CLIENT', 'CLIENT_INTERESTED'],
  BOOKING_REQUESTED: ['NEW', 'READY_FOR_SEARCH', 'ASSIGNED', 'SEARCHING', 'FARES_FOUND', 'PENDING_APPROVAL', 'APPROVED', 'QUOTED', 'AWAITING_CLIENT', 'BOOKING_REQUESTED'],
  TICKETING: ['NEW', 'READY_FOR_SEARCH', 'ASSIGNED', 'SEARCHING', 'FARES_FOUND', 'PENDING_APPROVAL', 'APPROVED', 'QUOTED', 'AWAITING_CLIENT', 'BOOKING_REQUESTED', 'TICKETING'],
  TICKETED: ['NEW', 'READY_FOR_SEARCH', 'ASSIGNED', 'SEARCHING', 'FARES_FOUND', 'PENDING_APPROVAL', 'APPROVED', 'QUOTED', 'AWAITING_CLIENT', 'BOOKING_REQUESTED', 'TICKETING', 'TICKETED'],
  CHANGE_REQUESTED: ['NEW', 'READY_FOR_SEARCH', 'ASSIGNED', 'SEARCHING', 'FARES_FOUND', 'PENDING_APPROVAL', 'APPROVED', 'QUOTED', 'AWAITING_CLIENT', 'BOOKING_REQUESTED', 'TICKETING', 'TICKETED', 'CHANGE_REQUESTED'],
  REFUND_REQUESTED: ['NEW', 'READY_FOR_SEARCH', 'ASSIGNED', 'SEARCHING', 'FARES_FOUND', 'PENDING_APPROVAL', 'APPROVED', 'QUOTED', 'AWAITING_CLIENT', 'BOOKING_REQUESTED', 'TICKETING', 'TICKETED', 'REFUND_REQUESTED'],
  LOST: ['NEW', 'READY_FOR_SEARCH', 'ASSIGNED', 'SEARCHING', 'FARES_FOUND', 'PENDING_APPROVAL', 'APPROVED', 'QUOTED', 'AWAITING_CLIENT', 'LOST'],
  CLOSED: ['NEW', 'READY_FOR_SEARCH', 'ASSIGNED', 'SEARCHING', 'FARES_FOUND', 'PENDING_APPROVAL', 'APPROVED', 'QUOTED', 'AWAITING_CLIENT', 'BOOKING_REQUESTED', 'TICKETING', 'TICKETED', 'CLOSED'],
  CANCELLED: ['NEW', 'READY_FOR_SEARCH', 'CANCELLED'],
};
const OPERATOR_BY_DESK = { PREMIUM_DESK: [100, 101], GROUP_DESK: [102], TICKETING_DESK: [103, 104], REFUND_DESK: [105], GENERAL_DESK: [106] };
const CITY = { DEL: 'Delhi', JFK: 'New York', DXB: 'Dubai', LHR: 'London', SIN: 'Singapore', NBO: 'Nairobi', BOM: 'Mumbai', MRU: 'Mauritius', CDG: 'Paris', YYZ: 'Toronto', BLR: 'Bengaluru', FRA: 'Frankfurt', HKG: 'Hong Kong', YUL: 'Montreal', JNB: 'Johannesburg', CPT: 'Cape Town', MIA: 'Miami', DOH: 'Doha' };

R.forEach((row, idx) => {
  const [ci, o, d, dep, ret, adults, cabin, status, createdAgo, statusAgo, channel, x] = row;
  const n = idx + 1;
  const c = contacts[ci];
  const rfqId = uuid('000000f0', n);
  const convId = uuid('000000cc', n);
  const msgId = uuid('000000ee', n);
  const depIso = addDays(TODAY, dep);
  const retIso = ret === null ? null : addDays(TODAY, ret);
  const delta = {
    intent: x.group ? 'GROUP_BOOKING' : x.change ? 'CHANGE_REQUEST' : x.refund ? 'CANCELLATION' : 'NEW_QUOTE',
    origin: { raw: CITY[o], iata: o }, destination: { raw: CITY[d], iata: d },
    departure_date: depIso, return_date: x.missingReturn ? null : retIso,
    trip_type: x.missingReturn ? 'ROUND_TRIP' : ret === null ? 'ONE_WAY' : 'ROUND_TRIP',
    passengers: x.missingPax ? null : { adults, children: 0, infants: 0 },
    cabin, urgency: x.urgent ? 'HIGH' : null, preferred_airlines: n % 3 === 0 ? ['Emirates'] : n % 3 === 1 ? ['Qatar Airways'] : [],
  };
  const { requirements } = mergeRequirements(null, delta);
  const prio = scorePriority({ intent: delta.intent, requirements, agency: { priority_level: c.vip ? 'VIP' : 'STANDARD' }, now: NOW }, cfg);
  const desk = ['NEW', 'NEEDS_INFORMATION', 'READY_FOR_SEARCH', 'CANCELLED'].includes(status) ? null : routeToDesk({ intent: delta.intent, status, requirements }, cfg).desk_code;
  const ticketingStage = ['BOOKING_REQUESTED', 'TICKETING', 'TICKETED', 'CHANGE_REQUESTED', 'REFUND_REQUESTED', 'CLOSED'].includes(status);
  const finalDesk = status === 'REFUND_REQUESTED' ? 'REFUND_DESK' : ticketingStage ? 'TICKETING_DESK' : desk;
  const opIdx = finalDesk ? OPERATOR_BY_DESK[finalDesk][n % OPERATOR_BY_DESK[finalDesk].length] : null;
  const threadKey = channel === 'email' ? `seed-thread-${n}` : c.wa;
  const text = channel === 'email'
    ? `Hi team,\n\nPlease quote ${adults} ${cabin.replace('_', ' ').toLowerCase()} pax ${CITY[o]} to ${CITY[d]} departing ${depIso}${retIso ? ` returning ${retIso}` : ' one way'}.\n\nThanks,\n${c.first}`
    : `${adults} pax ${o}-${d} ${cabin.toLowerCase()} ${depIso}${retIso ? ` ret ${retIso}` : ''}`;

  out.push(`-- RFQ ${n}: ${status}`);
  out.push(`INSERT INTO conversations (id, channel, external_thread_id, contact_id, agency_id, subject, last_inbound_at) VALUES ('${convId}', ${q(channel)}, ${q(channel === 'email' ? threadKey : `${threadKey}`)}, '${c.id}', '${c.agencyId}', ${q(channel === 'email' ? `Fare request ${o}-${d}` : null)}, ${ago(createdAgo)}) ON CONFLICT (channel, external_thread_id) DO NOTHING;`);
  const convRef = channel === 'whatsapp' ? `(SELECT id FROM conversations WHERE channel = 'whatsapp' AND external_thread_id = ${q(threadKey)})` : `'${convId}'`;
  out.push(`INSERT INTO rfqs (id, rfq_number, agency_id, contact_id, conversation_id, intent, trip_type, cabin, origin_iata, destination_iata, departure_date, return_date, adults, preferred_airlines, requirements, missing_fields, status, status_changed_at, priority_score, priority_level, priority_breakdown, assigned_team, assigned_user, source_channel, sla_breached, booking_reference, after_sales_type, is_demo, first_response_at, quoted_at, created_at, updated_at, closed_at) VALUES ('${rfqId}', format('OFF-RFQ-%s-%s', extract(year FROM now())::int, '${String(n).padStart(6, '0')}'), '${c.agencyId}', '${c.id}', ${convRef}, ${q(delta.intent)}, ${q(requirements.trip_type)}, ${q(cabin)}, ${q(o)}, ${q(d)}, ${day(dep)}, ${x.missingReturn ? 'NULL' : day(ret)}, ${x.missingPax ? 'NULL' : adults}, ${arr(requirements.preferred_airlines)}, ${j(requirements)}, ${arr(requirements.missing_fields)}, ${q(status)}, ${ago(statusAgo)}, ${prio.score}, ${q(prio.level)}, ${j(prio.breakdown)}, ${q(finalDesk)}, ${opIdx === null ? 'NULL' : `'${uuid('00000000', opIdx)}'`}, ${q(channel)}, ${x.slaBreached ? 'true' : 'false'}, ${q(x.pnr || null)}, ${q(x.change ? 'CHANGE' : x.refund ? 'CANCELLATION' : null)}, true, ${status === 'NEW' ? 'NULL' : ago(createdAgo - Math.min(4, createdAgo / 3))}, ${x.sent ? ago(statusAgo + 5) : 'NULL'}, ${ago(createdAgo)}, ${ago(Math.min(statusAgo, createdAgo))}, ${['LOST', 'CLOSED', 'CANCELLED'].includes(status) ? ago(statusAgo) : 'NULL'});`);
  out.push(`INSERT INTO messages (id, conversation_id, rfq_id, channel, direction, external_message_id, sender, subject, content, received_at, processed_at, processing_status, created_at) VALUES ('${msgId}', ${convRef}, '${rfqId}', ${q(channel)}, 'INBOUND', ${q(`seed-msg-${n}`)}, ${q(channel === 'email' ? c.email : c.wa)}, ${q(channel === 'email' ? `Fare request ${o}-${d}` : null)}, ${q(text)}, ${ago(createdAgo)}, ${ago(createdAgo - 0.2)}, 'PROCESSED', ${ago(createdAgo)});`);
  // passengers / segments
  if (!x.missingPax) out.push(`INSERT INTO rfq_passengers (rfq_id, pax_type, count) VALUES ('${rfqId}', 'ADT', ${adults});`);
  out.push(`INSERT INTO rfq_segments (rfq_id, seq, origin_iata, destination_iata, departure_date) VALUES ('${rfqId}', 1, ${q(o)}, ${q(d)}, ${day(dep)})${ret !== null && !x.missingReturn ? `, ('${rfqId}', 2, ${q(d)}, ${q(o)}, ${day(ret)})` : ''};`);
  // status history spread between creation and current status time
  const pathList = PATHS[status];
  pathList.forEach((s, i) => {
    const minutes = i === pathList.length - 1 ? statusAgo : createdAgo - ((createdAgo - statusAgo) * i) / Math.max(1, pathList.length - 1);
    out.push(`INSERT INTO rfq_status_history (rfq_id, from_status, to_status, actor_type, actor_id, reason, created_at) VALUES ('${rfqId}', ${i === 0 ? 'NULL' : q(pathList[i - 1])}, ${q(s)}, ${q(['APPROVED'].includes(s) ? 'HUMAN' : 'SYSTEM')}, 'seed', 'Demo history', ${ago(minutes)});`);
  });
  out.push(`INSERT INTO audit_logs (rfq_id, entity_type, entity_id, action, actor_type, actor_id, metadata, created_at) VALUES ('${rfqId}', 'rfq', '${rfqId}', 'RFQ_CREATED', 'SYSTEM', 'seed', '{"seed": true}', ${ago(createdAgo)}), ('${rfqId}', 'rfq', '${rfqId}', 'PRIORITY_CALCULATED', 'SYSTEM', 'seed', ${j({ score: prio.score, level: prio.level })}, ${ago(createdAgo - 0.1)});`);
  if (finalDesk) {
    out.push(`INSERT INTO assignments (rfq_id, desk_code, operator_id, rule, assigned_at) VALUES ('${rfqId}', ${q(finalDesk)}, '${uuid('00000000', opIdx)}', 'seed', ${ago(createdAgo - 1)});`);
  }
  // fare options + quotes
  if (x.quote || x.options) {
    const options = MockFareProvider.sampleOptions(requirements.passengers ? requirements : Object.assign({}, requirements, { passengers: { adults } }), NOW);
    const valid = validateFareOptions(options, { rfq: { trip_type: requirements.trip_type, cabin }, now: NOW });
    if (!valid.ok) throw new Error(`seed fare options invalid for RFQ ${n}: ${valid.errors.join('; ')}`);
    const validMinutesFromNow = x.sent ? -(statusAgo - 60) : 120; // sent quotes may already be expired
    valid.options.forEach((opt) => {
      out.push(`INSERT INTO fare_options (id, rfq_id, batch_no, option_no, option_code, airline, flight_segments, departure_at, arrival_at, return_departure_at, total_duration_minutes, stops, cabin, fare_amount, fare_currency, baggage, change_penalty, refund_penalty, fare_valid_until, source, entered_by, created_at) VALUES ('${uuid(`0000f${String(n).padStart(3, '0')}`, opt.option_no)}', '${rfqId}', 1, ${opt.option_no}, ${q(opt.option_code)}, ${q(opt.airline)}, ${j(opt.flight_segments)}, ${q(opt.departure_at)}, ${q(opt.arrival_at)}, ${q(opt.return_departure_at)}, ${opt.total_duration_minutes}, ${opt.stops}, ${q(opt.cabin)}, ${opt.fare.amount}, ${q(opt.fare.currency)}, ${q(opt.baggage)}, ${q(opt.change_penalty)}, ${q(opt.refund_penalty)}, now() + interval '${validMinutesFromNow} minutes', 'MOCK', ${q(operators[opIdx - 100] ? operators[opIdx - 100][1] : 'seed')}, ${ago(createdAgo / 2)});`);
    });
    if (x.quote) {
      const model = Q.buildQuoteModel({ rfq: { rfq_number: `OFF-RFQ-${NOW.getUTCFullYear()}-${String(n).padStart(6, '0')}` }, requirements: Object.assign({}, requirements, { passengers: { adults, children: 0, infants: 0 } }), contact: { first_name: c.first }, options: valid.options, timeZone: 'UTC', now: NOW });
      const email = Q.renderEmail(model, cfg.COMPANY_SIGNATURE);
      const wa = Q.renderWhatsApp(model);
      const quoteId = uuid('0000a000', n);
      const qStatus = x.sent ? 'SENT' : 'PENDING_APPROVAL';
      out.push(`INSERT INTO quotes (id, rfq_id, version, status, email_subject, email_body, whatsapp_body, quote_model, generated_by, validation, content_hash, valid_until, approved_by, approved_at, sent_at, delivery_channel, delivery_status, created_at) VALUES ('${quoteId}', '${rfqId}', 1, ${q(qStatus)}, ${q(email.subject)}, ${q(email.body)}, ${q(wa)}, ${j(model)}, 'TEMPLATE', '{"ok": true, "errors": []}', encode(digest(${q(email.subject + email.body + wa)}, 'sha256'), 'hex'), now() + interval '${validMinutesFromNow} minutes', ${x.sent ? q('Aisha Khan') : 'NULL'}, ${x.sent ? ago(statusAgo + 6) : 'NULL'}, ${x.sent ? ago(statusAgo + 5) : 'NULL'}, ${x.sent ? q(channel) : 'NULL'}, ${x.sent ? "'SIMULATED'" : 'NULL'}, ${ago(statusAgo + 8)});`);
      out.push(`INSERT INTO quote_options (quote_id, fare_option_id, display_order) SELECT '${quoteId}', id, option_no FROM fare_options WHERE rfq_id = '${rfqId}';`);
      if (x.sent) {
        out.push(`INSERT INTO approvals (quote_id, rfq_id, quote_version, action, approval_status, approved_by, approved_at, approval_note, content_hash, content_snapshot) VALUES ('${quoteId}', '${rfqId}', 1, 'APPROVE', 'APPROVED', 'Aisha Khan', ${ago(statusAgo + 6)}, 'Demo approval', 'seed', '{"seed": true}');`);
        out.push(`INSERT INTO messages (conversation_id, rfq_id, channel, direction, sender, recipient, subject, content, kind, sent_at, processing_status, delivery_status, created_at) VALUES (${convRef}, '${rfqId}', ${q(channel)}, 'OUTBOUND', 'Offshore Fares', ${q(channel === 'email' ? c.email : c.wa)}, ${q(channel === 'email' ? email.subject : null)}, ${q(channel === 'email' ? email.body : wa)}, 'QUOTE', ${ago(statusAgo + 5)}, 'SENT', 'SIMULATED', ${ago(statusAgo + 5)});`);
        out.push(`INSERT INTO audit_logs (rfq_id, entity_type, entity_id, action, actor_type, actor_id, metadata, created_at) VALUES ('${rfqId}', 'quote', '${quoteId}', 'QUOTE_SENT', 'SYSTEM', 'seed', ${j({ channel })}, ${ago(statusAgo + 5)});`);
        for (let f = 1; f <= (x.followups || 0); f += 1) {
          out.push(`INSERT INTO followups (rfq_id, quote_id, sequence_no, status, channel, sent_at) VALUES ('${rfqId}', '${quoteId}', ${f}, 'SENT', ${q(channel)}, ${ago(statusAgo - 240 * f)});`);
        }
      }
      if (x.selected) {
        out.push(`UPDATE rfqs SET selected_option_id = (SELECT id FROM fare_options WHERE rfq_id = '${rfqId}' AND option_no = ${x.selected}), booking_requested_at = ${ago(statusAgo)}, handoff = jsonb_build_object('rfq_number', rfq_number, 'selected_option', 'OPT-00${x.selected}', 'seed', true) WHERE id = '${rfqId}';`);
      }
    }
  }
  if (x.slaBreached) {
    out.push(`INSERT INTO alerts (rfq_id, alert_type, severity, desk_code, title, details, dedupe_key, created_at) VALUES ('${rfqId}', 'SLA_BREACH', 'WARNING', NULL, format('OFF-RFQ-%s-%s: SLA breached – waiting in READY_FOR_SEARCH', extract(year FROM now())::int, '${String(n).padStart(6, '0')}'), '{"seed": true}', 'SEED-SLA-${n}', ${ago(statusAgo - 10)});`);
  }
  if (finalDesk && ['ASSIGNED', 'BOOKING_REQUESTED', 'CHANGE_REQUESTED', 'REFUND_REQUESTED', 'PENDING_APPROVAL'].includes(status)) {
    out.push(`INSERT INTO alerts (rfq_id, alert_type, severity, desk_code, title, details, dedupe_key, created_at) VALUES ('${rfqId}', 'DESK_NOTIFICATION', ${q(prio.level === 'CRITICAL' ? 'CRITICAL' : prio.level === 'HIGH' ? 'WARNING' : 'INFO')}, ${q(finalDesk)}, format('OFF-RFQ-%s-%s: %s', extract(year FROM now())::int, '${String(n).padStart(6, '0')}', ${q(status === 'PENDING_APPROVAL' ? 'quote ready for approval' : status === 'BOOKING_REQUESTED' ? 'booking requested – ticketing handoff' : status === 'ASSIGNED' ? 'new request assigned' : 'after-sales request')}), '{"seed": true}', 'SEED-DESK-${n}', ${ago(statusAgo)});`);
  }
});

out.push(`INSERT INTO rfq_counters (year, last_value) VALUES (extract(year FROM now())::int, ${R.length}) ON CONFLICT (year) DO UPDATE SET last_value = greatest(rfq_counters.last_value, ${R.length});`);

// Knowledge base (non-sensitive) ------------------------------------------------
const kb = [
  ['office-hours', 'Fares desk opening hours', 'PROCESS', 'The Offshore Fares desk operates 24/7 for urgent travel within 72 hours. Standard quote requests are handled 08:00–22:00 (UTC+4), seven days a week. Requests received outside these hours are queued and prioritised automatically.', 'hours opening time weekend night'],
  ['quote-process', 'How quotes are prepared', 'PROCESS', 'Every request receives a reference (OFF-RFQ-YYYY-NNNNNN). Our fare desk searches the best available fares; each quote is reviewed by a team member before it is sent. Fares are not guaranteed until ticketed.', 'quote process fare validity reference'],
  ['mandatory-information', 'Information needed for a fare search', 'PROCESS', 'To search fares we need: origin and destination, travel dates (and return date for a return trip), number of passengers by type, and preferred cabin. Airline preferences and date flexibility help us find better fares.', 'information required details search'],
  ['booking-handoff', 'What happens after you choose an option', 'PROCESS', 'When you confirm an option, our ticketing desk revalidates the fare and availability, creates the booking and contacts you for passenger details and payment through the agreed secure process. No card details should be sent by email or WhatsApp.', 'booking ticketing payment passenger details'],
  ['changes-refunds', 'Changes, cancellations and refunds', 'POLICY', 'Change and refund conditions depend on the fare rules of each ticket. Send us the booking reference; the ticketing or refund desk will confirm the applicable penalties before anything is changed.', 'change cancel refund penalty rules'],
  ['documents', 'Travel documents', 'PROCESS', 'Passenger names must match passports exactly. Visa and passport validity checks remain the responsibility of the travel agency; our team can share airline guidance on request.', 'passport visa documents names'],
];
kb.forEach(([slug, title, cat, content, keywords]) => {
  out.push(`INSERT INTO knowledge_base (slug, title, category, content, keywords) VALUES (${q(slug)}, ${q(title)}, ${q(cat)}, ${q(content)}, ${q(keywords)});`);
});

out.push('COMMIT;');
const target = path.join(__dirname, '..', 'database', 'seed.sql');
fs.writeFileSync(target, `${out.join('\n')}\n`);
console.log(`Wrote ${target} (${R.length} RFQs, ${agencies.length} agencies, ${contacts.length} contacts)`);
